<?php
$this->load->view('layout/header');
$this->load->view('element/top_header');
$this->load->view('element/wrapper_header');
$this->load->view('element/left_panel');
$this->load->view('onlineshopping/new_buycodesSelectPackageForm'); 
$this->load->view('element/wrapper_footer');
$this->load->view('layout/footer');	
?>