<?php
    $this->load->view('layout/header');
    $this->load->view('element/wrapper_header');
    $this->load->view('hotels/nextrip/main_panel'); 
?>
<?php
    $this->load->view('element/wrapper_footer');
    $this->load->view('layout/footer');	
?>